import Foundation

enum AppLanguage: String {
    case vietnamese = "VI"
    case english = "EN"

    var next: AppLanguage {
        self == .vietnamese ? .english : .vietnamese
    }
}

enum AppText {
    static let values: [String: [AppLanguage: String]] = [
        "tab.home": [.vietnamese: "Trang chủ", .english: "Home"],
        "tab.discover": [.vietnamese: "Tìm nguồn", .english: "Source"],
        "discover.tab.title": [.vietnamese: "Tin đã duyệt", .english: "Approved listings"],
        "discover.title": [.vietnamese: "Yêu cầu đã duyệt", .english: "Approved requests"],
        "discover.subtitle": [.vietnamese: "Các nhu cầu sourcing đã qua kiểm tra ban đầu.", .english: "Sourcing needs that passed initial review."],
        "discover.empty.title": [.vietnamese: "Chưa có tin đã duyệt", .english: "No approved listings yet"],
        "discover.empty.body": [.vietnamese: "Các cơ hội phù hợp sẽ xuất hiện tại đây.", .english: "Suitable opportunities will appear here."],
        "discover.empty.intent.title": [.vietnamese: "Chưa có tin trong mục này", .english: "No listings in this tab"],
        "discover.empty.intent.body": [.vietnamese: "Khi có nhu cầu phù hợp, NexTrade sẽ hiển thị tại đây.", .english: "NexTrade will show relevant opportunities here when available."],
        "discover.approved": [.vietnamese: "Đã duyệt", .english: "Approved"],
        "discover.trade.prefix": [.vietnamese: "Giao dịch", .english: "Trade"],
        "discover.filter.all": [.vietnamese: "Tất cả thời gian", .english: "All time"],
        "discover.filter.yesterday": [.vietnamese: "Hôm qua", .english: "Yesterday"],
        "discover.filter.days7": [.vietnamese: "7 ngày gần đây", .english: "Last 7 days"],
        "discover.filter.days14": [.vietnamese: "14 ngày gần đây", .english: "Last 14 days"],
        "discover.filter.month": [.vietnamese: "1 tháng gần đây", .english: "Last month"],
        "discover.quantity": [.vietnamese: "Số lượng", .english: "Quantity"],
        "discover.market": [.vietnamese: "Thị trường", .english: "Market"],
        "discover.trade.time": [.vietnamese: "Thời điểm giao dịch", .english: "Trade time"],
        "discover.not.set": [.vietnamese: "Chưa cập nhật", .english: "Not specified"],
        "discover.verified.note": [.vietnamese: "NexTrade đã kiểm tra ban đầu và mở cơ hội này để kết nối.", .english: "NexTrade has completed an initial review and opened this opportunity."],
        "tab.requests": [.vietnamese: "Yêu cầu", .english: "Requests"],
        "tab.profile": [.vietnamese: "Hồ sơ", .english: "Profile"],

        "login.title": [.vietnamese: "Đăng nhập để gửi yêu cầu.", .english: "Sign in to submit your request."],
        "login.subtitle": [.vietnamese: "NexTrade cần xác nhận tài khoản trước khi tiếp nhận yêu cầu của bạn.", .english: "NexTrade needs to verify your account before receiving your request."],
        "login.email": [.vietnamese: "Email", .english: "Email"],
        "login.password": [.vietnamese: "Mật khẩu", .english: "Password"],
        "login.password.placeholder": [.vietnamese: "Nhập mật khẩu", .english: "Enter password"],
        "login.submit": [.vietnamese: "Đăng nhập", .english: "Sign in"],
        "login.dismiss": [.vietnamese: "Đóng", .english: "Close"],
        "login.error.required": [.vietnamese: "Vui lòng nhập email và mật khẩu.", .english: "Enter your email and password."],
        "login.error.failed": [.vietnamese: "Không thể đăng nhập. Kiểm tra lại thông tin hoặc kết nối máy chủ.", .english: "Unable to sign in. Check your details or server connection."],

        "home.subtitle": [.vietnamese: "Modern Trade OS", .english: "Modern Trade OS"],
        "home.hero.eyebrow": [.vietnamese: "B2B SOURCING PLATFORM", .english: "B2B SOURCING PLATFORM"],
        "home.hero.title": [.vietnamese: "TÌM NGUỒN HÀNG\nĐÁNG TIN CẬY.", .english: "RELIABLE SOURCING\nMADE SIMPLE."],
        "home.hero.description": [.vietnamese: "Gửi nhu cầu sản phẩm, số lượng và thị trường mục tiêu. NexTrade hỗ trợ kiểm tra thông tin và phản hồi phương án xử lý.", .english: "Submit your product needs, quantity, and target market. NexTrade helps review the request and respond with a handling plan."],
        "home.cta": [.vietnamese: "Gửi yêu cầu tìm nguồn", .english: "Submit sourcing request"],
        "home.snapshot.eyebrow": [.vietnamese: "VẬN HÀNH", .english: "OPERATIONS"],
        "home.snapshot.title": [.vietnamese: "Tổng quan yêu cầu", .english: "Request overview"],
        "home.snapshot.total": [.vietnamese: "Tổng yêu cầu", .english: "Total cases"],
        "home.snapshot.active": [.vietnamese: "Đang xử lý", .english: "In progress"],
        "home.snapshot.quoted": [.vietnamese: "Đã phản hồi", .english: "Quoted"],
        "home.recent.title": [.vietnamese: "Yêu cầu gần đây", .english: "Recent requests"],
        "home.recent.subtitle": [.vietnamese: "Theo dõi từng hồ sơ sourcing", .english: "Track every sourcing case"],
        "home.recent.all": [.vietnamese: "Xem tất cả", .english: "View all"],
        "home.recent.loading": [.vietnamese: "Đang tải hồ sơ...", .english: "Loading cases..."],
        "home.recent.empty.title": [.vietnamese: "Chưa có hồ sơ sourcing", .english: "No sourcing cases yet"],
        "home.recent.empty.body": [.vietnamese: "Gửi yêu cầu đầu tiên để bắt đầu theo dõi tiến độ.", .english: "Submit your first request to begin tracking progress."],
        "home.workflow": [.vietnamese: "Current workflow", .english: "Current workflow"],
        "home.workflow.submit": [.vietnamese: "Gửi nhu cầu", .english: "Submit need"],
        "home.workflow.review": [.vietnamese: "Kiểm tra nguồn", .english: "Review sources"],
        "home.workflow.response": [.vietnamese: "Phản hồi", .english: "Response"],
        "home.categories": [.vietnamese: "Nhóm hàng phổ biến", .english: "Popular categories"],
        "home.support": [.vietnamese: "NexTrade hỗ trợ", .english: "NexTrade support"],
        "home.value.source.title": [.vietnamese: "Tìm nguồn phù hợp", .english: "Matched sourcing"],
        "home.value.source.body": [.vietnamese: "Lọc nhu cầu và định hướng nguồn cung theo thị trường.", .english: "Clarify demand and map supply options by market."],
        "home.value.verify.title": [.vietnamese: "Xác minh cơ bản", .english: "Basic verification"],
        "home.value.verify.body": [.vietnamese: "Kiểm tra thông tin ban đầu trước khi kết nối.", .english: "Review basic supplier information before connecting."],
        "home.value.response.title": [.vietnamese: "Phản hồi nhanh", .english: "Fast response"],
        "home.value.response.body": [.vietnamese: "Tổng hợp phương án xử lý rõ ràng cho người mua.", .english: "Summarize a clear handling plan for buyers."],
        "home.art.source": [.vietnamese: "SOURCE", .english: "SOURCE"],
        "home.art.route": [.vietnamese: "Verified route", .english: "Verified route"],

        "category.fruit": [.vietnamese: "Trái cây", .english: "Fruit"],
        "category.vegetables": [.vietnamese: "Rau củ", .english: "Vegetables"],
        "category.dryFood": [.vietnamese: "Thực phẩm khô", .english: "Dry food"],
        "category.beverage": [.vietnamese: "Đồ uống", .english: "Beverages"],
        "category.other": [.vietnamese: "Hàng khác", .english: "Other goods"],

        "create.title": [.vietnamese: "Gửi yêu cầu", .english: "New request"],
        "create.trade.section": [.vietnamese: "Loại nhu cầu", .english: "Trade request"],
        "create.trade.intent": [.vietnamese: "Bạn muốn", .english: "You want to"],
        "create.trade.buy": [.vietnamese: "Mua", .english: "Buy"],
        "create.trade.sell": [.vietnamese: "Bán", .english: "Sell"],
        "create.trade.date": [.vietnamese: "Ngày cần giao dịch", .english: "Needed date"],
        "create.top.title": [.vietnamese: "Gửi yêu cầu tìm nguồn", .english: "Submit sourcing request"],
        "create.helper": [.vietnamese: "Thông tin càng rõ, NexTrade xử lý càng nhanh và phản hồi đúng nhu cầu hơn.", .english: "The clearer the details, the faster NexTrade can review and respond accurately."],
        "create.product.section": [.vietnamese: "Thông tin sản phẩm", .english: "Product information"],
        "create.product.name": [.vietnamese: "Tên sản phẩm", .english: "Product name"],
        "create.product.placeholder": [.vietnamese: "Ví dụ: xoài cát, sầu riêng, gạo ST25...", .english: "Example: mango, durian, ST25 rice..."],
        "create.category": [.vietnamese: "Nhóm hàng", .english: "Category"],
        "create.quantity": [.vietnamese: "Số lượng", .english: "Quantity"],
        "create.quantity.placeholder": [.vietnamese: "Ví dụ: 500kg, 1 tấn, 1 container...", .english: "Example: 500kg, 1 ton, 1 container..."],
        "create.market": [.vietnamese: "Thị trường mục tiêu", .english: "Target market"],
        "create.market.placeholder": [.vietnamese: "Ví dụ: Việt Nam, Trung Quốc, Hàn Quốc...", .english: "Example: Vietnam, China, Korea..."],
        "create.additional.section": [.vietnamese: "Yêu cầu thêm", .english: "Additional requirements"],
        "create.budget": [.vietnamese: "Ngân sách", .english: "Budget"],
        "create.budget.placeholder": [.vietnamese: "Ngân sách dự kiến nếu có", .english: "Expected budget if available"],
        "create.note": [.vietnamese: "Ghi chú", .english: "Note"],
        "create.note.placeholder": [.vietnamese: "Yêu cầu thêm về chất lượng, đóng gói, chứng từ...", .english: "Quality, packaging, document requirements..."],
        "create.contact.section": [.vietnamese: "Thông tin liên hệ", .english: "Contact information"],
        "create.contact.subtitle": [.vietnamese: "Cần số điện thoại hoặc email để NexTrade phản hồi.", .english: "Phone number or email is required for NexTrade to respond."],
        "create.contact.name": [.vietnamese: "Tên người liên hệ", .english: "Contact name"],
        "create.phone": [.vietnamese: "Số điện thoại", .english: "Phone number"],
        "create.email": [.vietnamese: "Email", .english: "Email"],
        "create.submit": [.vietnamese: "Gửi yêu cầu", .english: "Submit request"],
        "create.alert.title": [.vietnamese: "Đã gửi yêu cầu", .english: "Request submitted"],
        "create.alert.ok": [.vietnamese: "Đồng ý", .english: "OK"],
        "create.alert.message": [.vietnamese: "Yêu cầu của bạn đã được gửi. NexTrade sẽ liên hệ lại sau khi kiểm tra thông tin.", .english: "Your request has been submitted. NexTrade will contact you after reviewing the information."],
        "error.submit": [.vietnamese: "Không thể gửi yêu cầu lúc này. Vui lòng thử lại sau.", .english: "Unable to submit the request now. Please try again later."],
        "error.session": [.vietnamese: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.", .english: "Your session has expired. Please sign in again."],
        "error.permission": [.vietnamese: "Tài khoản của bạn không có quyền thực hiện thao tác này.", .english: "Your account does not have permission for this action."],
        "error.request.invalid": [.vietnamese: "Thông tin gửi lên chưa hợp lệ. Vui lòng kiểm tra lại các trường bắt buộc.", .english: "Some submitted information is invalid. Please check the required fields."],
        "error.email.invalid": [.vietnamese: "Email chưa đúng định dạng.", .english: "Enter a valid email address."],
        "error.phone.invalid": [.vietnamese: "Số điện thoại cần có từ 9 đến 15 chữ số.", .english: "Phone number must contain 9 to 15 digits."],
        "error.product.required": [.vietnamese: "Vui lòng nhập tên sản phẩm cần tìm nguồn.", .english: "Please enter the product name."],
        "error.category.required": [.vietnamese: "Vui lòng chọn nhóm hàng.", .english: "Please select a category."],
        "error.contact.required": [.vietnamese: "Vui lòng nhập số điện thoại hoặc email để NexTrade liên hệ lại.", .english: "Please enter a phone number or email so NexTrade can contact you."],

        "requests.title": [.vietnamese: "Yêu cầu", .english: "Requests"],
        "requests.queue": [.vietnamese: "Yêu cầu đã gửi", .english: "Submitted requests"],
        "requests.loading": [.vietnamese: "Đang tải yêu cầu...", .english: "Loading requests..."],
        "requests.empty.title": [.vietnamese: "Chưa có yêu cầu nào", .english: "No requests yet"],
        "requests.empty.description": [.vietnamese: "Khi bạn gửi yêu cầu tìm nguồn hàng, danh sách sẽ hiển thị tại đây.", .english: "When you submit sourcing requests, they will appear here."],
        "requests.guest.title": [.vietnamese: "Chưa có yêu cầu để theo dõi", .english: "No requests to track yet"],
        "requests.guest.body": [.vietnamese: "Gửi một yêu cầu tìm nguồn để NexTrade tạo hồ sơ theo dõi cho bạn.", .english: "Submit a sourcing request and NexTrade will create a case for you to track."],
        "requests.search.placeholder": [.vietnamese: "Tìm theo sản phẩm hoặc thị trường", .english: "Search product or market"],
        "requests.filter.title": [.vietnamese: "Lọc theo trạng thái", .english: "Filter by status"],
        "requests.filter.all": [.vietnamese: "Tất cả", .english: "All"],
        "requests.filter.empty.title": [.vietnamese: "Không có yêu cầu phù hợp", .english: "No matching requests"],
        "requests.filter.empty.description": [.vietnamese: "Thử đổi trạng thái lọc hoặc từ khóa tìm kiếm.", .english: "Try a different status or search term."],
        "requests.row.note": [.vietnamese: "NexTrade đang ghi nhận và xử lý hồ sơ", .english: "NexTrade is reviewing this case"],
        "error.load": [.vietnamese: "Không thể tải danh sách yêu cầu. Vui lòng thử lại sau.", .english: "Unable to load requests. Please try again later."],

        "detail.title": [.vietnamese: "Chi tiết yêu cầu", .english: "Request detail"],
        "detail.created": [.vietnamese: "Ngày tạo", .english: "Created"],
        "detail.product.section": [.vietnamese: "Thông tin sản phẩm", .english: "Product information"],
        "detail.contact.section": [.vietnamese: "Thông tin liên hệ", .english: "Contact information"],
        "detail.admin.note": [.vietnamese: "Ghi chú từ NexTrade", .english: "NexTrade note"],
        "detail.category": [.vietnamese: "Nhóm hàng", .english: "Category"],
        "detail.quantity": [.vietnamese: "Số lượng", .english: "Quantity"],
        "detail.market": [.vietnamese: "Thị trường mục tiêu", .english: "Target market"],
        "detail.trade.intent": [.vietnamese: "Nhu cầu", .english: "Intent"],
        "detail.trade.time": [.vietnamese: "Ngày giao dịch", .english: "Trade date"],
        "detail.budget": [.vietnamese: "Ngân sách", .english: "Budget"],
        "detail.note": [.vietnamese: "Ghi chú", .english: "Note"],
        "detail.status": [.vietnamese: "Trạng thái", .english: "Status"],
        "detail.contact.name": [.vietnamese: "Người liên hệ", .english: "Contact person"],
        "detail.phone": [.vietnamese: "Số điện thoại", .english: "Phone number"],
        "detail.email": [.vietnamese: "Email", .english: "Email"],
        "detail.content": [.vietnamese: "Nội dung", .english: "Content"],
        "detail.not.provided": [.vietnamese: "Chưa cung cấp", .english: "Not provided"],

        "profile.title": [.vietnamese: "Hồ sơ", .english: "Profile"],
        "profile.service": [.vietnamese: "Business sourcing service", .english: "Business sourcing service"],
        "profile.summary": [.vietnamese: "NexTrade hỗ trợ cá nhân, shop và doanh nghiệp nhỏ tìm nguồn hàng nông sản, thực phẩm và sản phẩm xuất nhập khẩu.", .english: "NexTrade helps individuals, shops, and small businesses source agriculture, food, and import-export products."],
        "profile.contact": [.vietnamese: "Liên hệ", .english: "Contact"],
        "profile.current.services": [.vietnamese: "Dịch vụ hiện tại", .english: "Current services"],
        "profile.updating": [.vietnamese: "Đang cập nhật", .english: "Updating"],
        "profile.in.progress": [.vietnamese: "Đang triển khai", .english: "Active"],
        "profile.logout": [.vietnamese: "Đăng xuất", .english: "Sign out"],
        "service.sourcing": [.vietnamese: "Tìm nguồn hàng theo yêu cầu", .english: "Sourcing by request"],
        "service.verify": [.vietnamese: "Kiểm tra thông tin nhà cung cấp cơ bản", .english: "Basic supplier verification"],
        "service.quote": [.vietnamese: "Hỗ trợ báo giá và kết nối ban đầu", .english: "Quote support and initial connection"],

        "status.new.title": [.vietnamese: "Yêu cầu mới", .english: "New request"],
        "status.reviewing.title": [.vietnamese: "Đang kiểm tra", .english: "Reviewing"],
        "status.quoted.title": [.vietnamese: "Đã phản hồi giá", .english: "Quoted"],
        "status.completed.title": [.vietnamese: "Hoàn tất", .english: "Completed"],
        "status.cancelled.title": [.vietnamese: "Đã hủy", .english: "Cancelled"],
        "status.new.badge": [.vietnamese: "Mới", .english: "New"],
        "status.reviewing.badge": [.vietnamese: "Đang xử lý", .english: "Reviewing"],
        "status.quoted.badge": [.vietnamese: "Có báo giá", .english: "Quoted"],
        "status.completed.badge": [.vietnamese: "Hoàn tất", .english: "Done"],
        "status.cancelled.badge": [.vietnamese: "Đã hủy", .english: "Cancelled"]
    ]
}
